spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost/backend_practica
    username: postgres
    password: sc0lllly93

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

feign:
   hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /