spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost/backend_practica
    username: postgres
    password: sc0lllly93

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/